/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: src/sanity/extract.json
export type CustomSchema = {
  knowsAbout?: string;
  hasOfferCatalog?: Array<string>;
};

export type HeroSplitModule = {
  _type: "heroSplitModule";
  name: string;
};

export type Modules = Array<
  {
    _key: string;
  } & HeroSplitModule
>;

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type SeoObject = {
  _type: "seoObject";
  metaTitle?: string;
  metaDescription?: string;
  ogImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  canonicalUrl?: string;
  robotsIndex?: "index" | "noindex";
  robotsFollow?: "follow" | "nofollow";
  schemaType?:
    | "Organization"
    | "Service"
    | "Project"
    | "Article"
    | "LocalBusiness";
  customSchema?: CustomSchema;
  ogTitle?: string;
  ogDescription?: string;
  twitterCard?: "summary_large_image" | "summary";
};

export type PageReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "page";
};

export type AboutReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "about";
};

export type JournalReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "journal";
};

export type ProjectReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "project";
};

export type ServiceReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "service";
};

export type ResearchReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "research";
};

export type PressReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "press";
};

export type LinkObject = {
  _type: "linkObject";
  name: string;
  type: "internal" | "external";
  page?:
    | PageReference
    | AboutReference
    | JournalReference
    | ProjectReference
    | ServiceReference
    | ResearchReference
    | PressReference;
  href?: string;
  target: "_self" | "_blank";
};

export type GridDimensionObject = {
  _type: "gridDimensionObject";
  isBig?: boolean;
};

export type ContentObject = {
  _type: "contentObject";
  content: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?:
          | "normal"
          | "h1"
          | "h2"
          | "h3"
          | "h4"
          | "h5"
          | "h6"
          | "blockquote";
        listItem?: "bullet" | "number";
        markDefs?: Array<
          | {
              href?: string;
              blank?: boolean;
              _type: "link";
              _key: string;
            }
          | {
              reference?:
                | PageReference
                | JournalReference
                | ProjectReference
                | ServiceReference
                | ResearchReference
                | PressReference
                | AboutReference;
              _type: "internalLink";
              _key: string;
            }
        >;
        level?: number;
        _type: "block";
        _key: string;
      }
    | ({
        _key: string;
      } & ImageObject)
  >;
};

export type ImageObject = {
  _type: "imageObject";
  image: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  altContent?: string;
  caption?: string;
};

export type TitleSlugObject = {
  _type: "titleSlugObject";
  name: string;
  slug: Slug;
};

export type Redirect = {
  _id: string;
  _type: "redirect";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  source: string;
  destination: string;
  permanent?: boolean;
  isActive?: boolean;
  notes?: string;
};

export type Customer = {
  _id: string;
  _type: "customer";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name: string;
  mainImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  shortDescription?: string;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top: number;
  bottom: number;
  left: number;
  right: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x: number;
  y: number;
  height: number;
  width: number;
};

export type UnGoal = {
  _id: string;
  _type: "unGoal";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name: string;
  logoPositive: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  logoNegative: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
};

export type Organization = {
  _id: string;
  _type: "organization";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name: string;
  type: "client" | "partner" | "sponsor";
  logoDark: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  logoLight?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
};

export type Navigation = {
  _id: string;
  _type: "navigation";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name: string;
  links?: Array<
    {
      _key: string;
    } & LinkObject
  >;
};

export type Process = {
  _id: string;
  _type: "process";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name: string;
};

export type Capability = {
  _id: string;
  _type: "capability";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name: string;
};

export type Site = {
  _id: string;
  _type: "site";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name: string;
  seo?: SeoObject;
};

export type Glossary = {
  _id: string;
  _type: "glossary";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name: string;
  slug: Slug;
  image?: ImageObject;
  definition?: string;
};

export type Slug = {
  _type: "slug";
  current: string;
  source?: string;
};

export type TagReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "tag";
};

export type Journal = {
  _id: string;
  _type: "journal";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name: string;
  slug: Slug;
  gridDimension?: GridDimensionObject;
  tag: TagReference;
  location: string;
  publishingDate: string;
  mainImage: ImageObject;
  shortDescription: string;
  contentObject: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?:
          | "normal"
          | "h1"
          | "h2"
          | "h3"
          | "h4"
          | "h5"
          | "h6"
          | "blockquote";
        listItem?: "bullet" | "number";
        markDefs?: Array<
          | {
              href?: string;
              blank?: boolean;
              _type: "link";
              _key: string;
            }
          | {
              reference?:
                | PageReference
                | JournalReference
                | ProjectReference
                | ServiceReference
                | ResearchReference
                | PressReference
                | AboutReference;
              _type: "internalLink";
              _key: string;
            }
        >;
        level?: number;
        _type: "block";
        _key: string;
      }
    | ({
        _key: string;
      } & ImageObject)
  >;
  relatedService?: ServiceReference;
  relatedProject?: ProjectReference;
  relatedResearch?: ResearchReference;
  seo?: SeoObject;
};

export type Project = {
  _id: string;
  _type: "project";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name: string;
  slug: Slug;
  mainImage: ImageObject;
  status:
    | "on-hold"
    | "in-progress"
    | "in-construction"
    | "completed"
    | "cancelled";
  location?: string;
  areaRestored?: string;
  interventionType?: string;
  shortDescription?: string;
  pageContent?: ContentObject;
  relatedService?: ServiceReference;
  relatedResearch?: ResearchReference;
  seo?: SeoObject;
};

export type OrganizationReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "organization";
};

export type CapabilityReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "capability";
};

export type Service = {
  _id: string;
  _type: "service";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name: string;
  slug: Slug;
  shortDescription?: string;
  mainImage: ImageObject;
  clients?: Array<
    {
      _key: string;
    } & OrganizationReference
  >;
  capabilities?: Array<
    {
      _key: string;
    } & CapabilityReference
  >;
  content?: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?:
          | "normal"
          | "h1"
          | "h2"
          | "h3"
          | "h4"
          | "h5"
          | "h6"
          | "blockquote";
        listItem?: "bullet" | "number";
        markDefs?: Array<
          | {
              href?: string;
              blank?: boolean;
              _type: "link";
              _key: string;
            }
          | {
              reference?:
                | PageReference
                | JournalReference
                | ProjectReference
                | ServiceReference
                | ResearchReference
                | PressReference
                | AboutReference;
              _type: "internalLink";
              _key: string;
            }
        >;
        level?: number;
        _type: "block";
        _key: string;
      }
    | ({
        _key: string;
      } & ImageObject)
  >;
  relatedProject?: Array<
    {
      _key: string;
    } & ProjectReference
  >;
  relatedResearch?: Array<
    {
      _key: string;
    } & ResearchReference
  >;
  seo?: SeoObject;
};

export type About = {
  _id: string;
  _type: "about";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name: string;
};

export type Press = {
  _id: string;
  _type: "press";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name: string;
};

export type Research = {
  _id: string;
  _type: "research";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  titleSlug: TitleSlugObject;
  mainImage: ImageObject;
  relatedService?: ServiceReference;
  relatedProject?: ProjectReference;
};

export type Page = {
  _id: string;
  _type: "page";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name: string;
  slug: Slug;
  mainImage: ImageObject;
  modules?: Array<
    {
      _key: string;
    } & HeroSplitModule
  >;
  seo?: SeoObject;
};

export type Tag = {
  _id: string;
  _type: "tag";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name: string;
  slug: Slug;
};

export type MediaTag = {
  _id: string;
  _type: "media.tag";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: Slug;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height: number;
  width: number;
  aspectRatio: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | CustomSchema
  | HeroSplitModule
  | Modules
  | SanityImageAssetReference
  | SeoObject
  | PageReference
  | AboutReference
  | JournalReference
  | ProjectReference
  | ServiceReference
  | ResearchReference
  | PressReference
  | LinkObject
  | GridDimensionObject
  | ContentObject
  | ImageObject
  | TitleSlugObject
  | Redirect
  | Customer
  | SanityImageCrop
  | SanityImageHotspot
  | UnGoal
  | Organization
  | Navigation
  | Process
  | Capability
  | Site
  | Glossary
  | Slug
  | TagReference
  | Journal
  | Project
  | OrganizationReference
  | CapabilityReference
  | Service
  | About
  | Press
  | Research
  | Page
  | Tag
  | MediaTag
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: src/app/(frontend)/_sections/logos.tsx
// Variable: ORGANIZATIONS_QUERY
// Query: *[_type == "organization"]{  _id,  name,  type,  logoDark{    _type,    asset->{      _id,      url,    }  },}
export type ORGANIZATIONS_QUERY_RESULT = Array<{
  _id: string;
  name: string;
  type: "client" | "partner" | "sponsor";
  logoDark: {
    _type: "image";
    asset: {
      _id: string;
      url: string | null;
    } | null;
  };
}>;

// Source: src/app/sitemap.ts
// Variable: PROJECTS_SITEMAP_QUERY
// Query: *[_type == "project" && defined(slug.current) && seo.robotsIndex != "noindex"] {    "slug": slug.current,    _updatedAt  }
export type PROJECTS_SITEMAP_QUERY_RESULT = Array<{
  slug: string;
  _updatedAt: string;
}>;

// Source: src/app/sitemap.ts
// Variable: JOURNAL_SITEMAP_QUERY
// Query: *[_type == "journal" && defined(slug.current) && seo.robotsIndex != "noindex"] {    "slug": slug.current,    _updatedAt  }
export type JOURNAL_SITEMAP_QUERY_RESULT = Array<{
  slug: string;
  _updatedAt: string;
}>;

// Source: src/app/sitemap.ts
// Variable: SERVICES_SITEMAP_QUERY
// Query: *[_type == "service" && defined(slug.current) && seo.robotsIndex != "noindex"] {    "slug": slug.current,    _updatedAt  }
export type SERVICES_SITEMAP_QUERY_RESULT = Array<{
  slug: string;
  _updatedAt: string;
}>;

// Source: src/sanity/lib/queries.ts
// Variable: SITE_SETTINGS_QUERY
// Query: *[_type == "site" && _id == "site"][0]{  name,  seo{    metaTitle,    metaDescription,    ogImage{      asset->{        _id,        url      }    },    canonicalUrl,    robotsIndex,    robotsFollow,    ogTitle,    ogDescription,    twitterCard  }}
export type SITE_SETTINGS_QUERY_RESULT = {
  name: string;
  seo: {
    metaTitle: string | null;
    metaDescription: string | null;
    ogImage: {
      asset: {
        _id: string;
        url: string | null;
      } | null;
    } | null;
    canonicalUrl: string | null;
    robotsIndex: "index" | "noindex" | null;
    robotsFollow: "follow" | "nofollow" | null;
    ogTitle: string | null;
    ogDescription: string | null;
    twitterCard: "summary_large_image" | "summary" | null;
  } | null;
} | null;

// Source: src/sanity/lib/queries.ts
// Variable: PROJECTS_QUERY
// Query: *[_type == "project" && defined(slug.current)] {  _id,  name,  slug,  shortDescription,  gridDimension{    isBig  },  mainImage{    _type,    image{      _type,      asset->{        _id,        url      }    }  },  tag->{    _id,    name  }}
export type PROJECTS_QUERY_RESULT = Array<{
  _id: string;
  name: string;
  slug: Slug;
  shortDescription: string | null;
  gridDimension: null;
  mainImage: {
    _type: "imageObject";
    image: {
      _type: "image";
      asset: {
        _id: string;
        url: string | null;
      } | null;
    };
  };
  tag: null;
}>;

// Source: src/sanity/lib/queries.ts
// Variable: JOURNAL_QUERY
// Query: *[_type == "journal" && defined(slug.current)] | order(publishingDate desc){  _id,  name,  slug,  shortDescription,  gridDimension{    isBig  },  mainImage{    _type,    image{      _type,      asset->{        _id,        url      }    }  },  publishingDate,  tag->{    _id,    name  }}
export type JOURNAL_QUERY_RESULT = Array<{
  _id: string;
  name: string;
  slug: Slug;
  shortDescription: string;
  gridDimension: {
    isBig: boolean | null;
  } | null;
  mainImage: {
    _type: "imageObject";
    image: {
      _type: "image";
      asset: {
        _id: string;
        url: string | null;
      } | null;
    };
  };
  publishingDate: string;
  tag: {
    _id: string;
    name: string;
  };
}>;

// Source: src/sanity/lib/queries.ts
// Variable: JOURNAL_ITEM_QUERY
// Query: *[_type == "journal" && slug.current == $slug][0]{  _id,  name,  slug,  mainImage{    _type,    image{      _type,      asset->{        _id,        url      }    }  },  location,  publishingDate,  shortDescription,  contentObject[]{    ...,    _type == "block" => {      ...,      markDefs[]{        ...,        _type == "internalLink" => {          ...,          "slug": reference->slug.current,          "type": reference->_type        }      }    },    _type == "imageObject" => {      ...,      image{        ...,        hotspot,        crop,        asset->{          _id,          url,          metadata{            dimensions{              width,              height,              aspectRatio            }          }        }      }    }  },  tag->{    _id,    name  },  seo{    metaTitle,    metaDescription,    ogImage{      asset->{        _id,        url      }    },    canonicalUrl,    robotsIndex,    robotsFollow,    schemaType,    customSchema{      knowsAbout,      hasOfferCatalog    },    ogTitle,    ogDescription,    twitterCard  }}
export type JOURNAL_ITEM_QUERY_RESULT = {
  _id: string;
  name: string;
  slug: Slug;
  mainImage: {
    _type: "imageObject";
    image: {
      _type: "image";
      asset: {
        _id: string;
        url: string | null;
      } | null;
    };
  };
  location: string;
  publishingDate: string;
  shortDescription: string;
  contentObject: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?:
          | "blockquote"
          | "h1"
          | "h2"
          | "h3"
          | "h4"
          | "h5"
          | "h6"
          | "normal";
        listItem?: "bullet" | "number";
        markDefs: Array<
          | {
              reference?:
                | AboutReference
                | JournalReference
                | PageReference
                | PressReference
                | ProjectReference
                | ResearchReference
                | ServiceReference;
              _type: "internalLink";
              _key: string;
              slug: string | null;
              type:
                | "about"
                | "journal"
                | "page"
                | "press"
                | "project"
                | "research"
                | "service"
                | null;
            }
          | {
              href?: string;
              blank?: boolean;
              _type: "link";
              _key: string;
            }
        > | null;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        _key: string;
        _type: "imageObject";
        image: {
          asset: {
            _id: string;
            url: string | null;
            metadata: {
              dimensions: {
                width: number;
                height: number;
                aspectRatio: number;
              } | null;
            } | null;
          } | null;
          media?: unknown;
          hotspot: SanityImageHotspot | null;
          crop: SanityImageCrop | null;
          _type: "image";
        };
        altContent?: string;
        caption?: string;
      }
  >;
  tag: {
    _id: string;
    name: string;
  };
  seo: {
    metaTitle: string | null;
    metaDescription: string | null;
    ogImage: {
      asset: {
        _id: string;
        url: string | null;
      } | null;
    } | null;
    canonicalUrl: string | null;
    robotsIndex: "index" | "noindex" | null;
    robotsFollow: "follow" | "nofollow" | null;
    schemaType:
      | "Article"
      | "LocalBusiness"
      | "Organization"
      | "Project"
      | "Service"
      | null;
    customSchema: {
      knowsAbout: string | null;
      hasOfferCatalog: Array<string> | null;
    } | null;
    ogTitle: string | null;
    ogDescription: string | null;
    twitterCard: "summary_large_image" | "summary" | null;
  } | null;
} | null;

// Source: src/sanity/lib/queries.ts
// Variable: TAGS_QUERY
// Query: *[_type == "tag"] | order(name asc){  _id,  name,  slug}
export type TAGS_QUERY_RESULT = Array<{
  _id: string;
  name: string;
  slug: Slug;
}>;

// Source: src/sanity/lib/queries.ts
// Variable: SERVICES_QUERY
// Query: *[_type == "service" && defined(slug.current)] | order(name asc){  _id,  name,  slug,  shortDescription,  mainImage{    _type,    image{      _type,      asset->{        _id,        url      }    }  }}
export type SERVICES_QUERY_RESULT = Array<{
  _id: string;
  name: string;
  slug: Slug;
  shortDescription: string | null;
  mainImage: {
    _type: "imageObject";
    image: {
      _type: "image";
      asset: {
        _id: string;
        url: string | null;
      } | null;
    };
  };
}>;

// Source: src/sanity/lib/queries.ts
// Variable: SERVICE_QUERY
// Query: *[_type == "service" && slug.current == $slug][0]{  _id,  name,  slug,  shortDescription,  content[]{    ...,    _type == "block" => {      ...,      markDefs[]{        ...,        _type == "internalLink" => {          ...,          "slug": reference->slug.current,          "type": reference->_type        }      }    },    _type == "imageObject" => {      ...,      image{        ...,        hotspot,        crop,        asset->{          _id,          url,          metadata{            dimensions{              width,              height,              aspectRatio            }          }        }      }    }  },  capabilities[]->{    _id,    name  },  clients[]->{    _id,    name,    logoDark{      asset->{        _id,        _type,        url      }    }  },  mainImage{    image{      asset->{        url      }    }  },  seo{    metaTitle,    metaDescription,    ogImage{      asset->{        _id,        url      }    },    canonicalUrl,    robotsIndex,    robotsFollow,    schemaType,    customSchema{      knowsAbout,      hasOfferCatalog    },    ogTitle,    ogDescription,    twitterCard  }}
export type SERVICE_QUERY_RESULT = {
  _id: string;
  name: string;
  slug: Slug;
  shortDescription: string | null;
  content: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?:
          | "blockquote"
          | "h1"
          | "h2"
          | "h3"
          | "h4"
          | "h5"
          | "h6"
          | "normal";
        listItem?: "bullet" | "number";
        markDefs: Array<
          | {
              reference?:
                | AboutReference
                | JournalReference
                | PageReference
                | PressReference
                | ProjectReference
                | ResearchReference
                | ServiceReference;
              _type: "internalLink";
              _key: string;
              slug: string | null;
              type:
                | "about"
                | "journal"
                | "page"
                | "press"
                | "project"
                | "research"
                | "service"
                | null;
            }
          | {
              href?: string;
              blank?: boolean;
              _type: "link";
              _key: string;
            }
        > | null;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        _key: string;
        _type: "imageObject";
        image: {
          asset: {
            _id: string;
            url: string | null;
            metadata: {
              dimensions: {
                width: number;
                height: number;
                aspectRatio: number;
              } | null;
            } | null;
          } | null;
          media?: unknown;
          hotspot: SanityImageHotspot | null;
          crop: SanityImageCrop | null;
          _type: "image";
        };
        altContent?: string;
        caption?: string;
      }
  > | null;
  capabilities: Array<{
    _id: string;
    name: string;
  }> | null;
  clients: Array<{
    _id: string;
    name: string;
    logoDark: {
      asset: {
        _id: string;
        _type: "sanity.imageAsset";
        url: string | null;
      } | null;
    };
  }> | null;
  mainImage: {
    image: {
      asset: {
        url: string | null;
      } | null;
    };
  };
  seo: {
    metaTitle: string | null;
    metaDescription: string | null;
    ogImage: {
      asset: {
        _id: string;
        url: string | null;
      } | null;
    } | null;
    canonicalUrl: string | null;
    robotsIndex: "index" | "noindex" | null;
    robotsFollow: "follow" | "nofollow" | null;
    schemaType:
      | "Article"
      | "LocalBusiness"
      | "Organization"
      | "Project"
      | "Service"
      | null;
    customSchema: {
      knowsAbout: string | null;
      hasOfferCatalog: Array<string> | null;
    } | null;
    ogTitle: string | null;
    ogDescription: string | null;
    twitterCard: "summary_large_image" | "summary" | null;
  } | null;
} | null;

// Source: src/sanity/lib/queries.ts
// Variable: PROJECT_ITEM_QUERY
// Query: *[_type == "project" && slug.current == $slug][0]{  _id,  name,  slug,  mainImage{    _type,    image{      _type,      asset->{        _id,        url      }    }  },  status,  location,  areaRestored,  interventionType,  shortDescription,  pageContent{    content[]{      ...,      _type == "block" => {        ...,        markDefs[]{          ...,          _type == "internalLink" => {            ...,            "slug": reference->slug.current,            "type": reference->_type          }        }      },      _type == "imageObject" => {        ...,        image{          ...,          hotspot,          crop,          asset->{            _id,            url,            metadata{              dimensions{                width,                height,                aspectRatio              }            }          }        }      }    }  },  relatedService->{    _id,    name,    slug  },  relatedResearch->{    _id,    name  },  seo{    metaTitle,    metaDescription,    ogImage{      asset->{        _id,        url      }    },    canonicalUrl,    robotsIndex,    robotsFollow,    schemaType,    customSchema{      knowsAbout,      hasOfferCatalog    },    ogTitle,    ogDescription,    twitterCard  }}
export type PROJECT_ITEM_QUERY_RESULT = {
  _id: string;
  name: string;
  slug: Slug;
  mainImage: {
    _type: "imageObject";
    image: {
      _type: "image";
      asset: {
        _id: string;
        url: string | null;
      } | null;
    };
  };
  status:
    | "cancelled"
    | "completed"
    | "in-construction"
    | "in-progress"
    | "on-hold";
  location: string | null;
  areaRestored: string | null;
  interventionType: string | null;
  shortDescription: string | null;
  pageContent: {
    content: Array<
      | {
          children?: Array<{
            marks?: Array<string>;
            text?: string;
            _type: "span";
            _key: string;
          }>;
          style?:
            | "blockquote"
            | "h1"
            | "h2"
            | "h3"
            | "h4"
            | "h5"
            | "h6"
            | "normal";
          listItem?: "bullet" | "number";
          markDefs: Array<
            | {
                reference?:
                  | AboutReference
                  | JournalReference
                  | PageReference
                  | PressReference
                  | ProjectReference
                  | ResearchReference
                  | ServiceReference;
                _type: "internalLink";
                _key: string;
                slug: string | null;
                type:
                  | "about"
                  | "journal"
                  | "page"
                  | "press"
                  | "project"
                  | "research"
                  | "service"
                  | null;
              }
            | {
                href?: string;
                blank?: boolean;
                _type: "link";
                _key: string;
              }
          > | null;
          level?: number;
          _type: "block";
          _key: string;
        }
      | {
          _key: string;
          _type: "imageObject";
          image: {
            asset: {
              _id: string;
              url: string | null;
              metadata: {
                dimensions: {
                  width: number;
                  height: number;
                  aspectRatio: number;
                } | null;
              } | null;
            } | null;
            media?: unknown;
            hotspot: SanityImageHotspot | null;
            crop: SanityImageCrop | null;
            _type: "image";
          };
          altContent?: string;
          caption?: string;
        }
    >;
  } | null;
  relatedService: {
    _id: string;
    name: string;
    slug: Slug;
  } | null;
  relatedResearch: {
    _id: string;
    name: null;
  } | null;
  seo: {
    metaTitle: string | null;
    metaDescription: string | null;
    ogImage: {
      asset: {
        _id: string;
        url: string | null;
      } | null;
    } | null;
    canonicalUrl: string | null;
    robotsIndex: "index" | "noindex" | null;
    robotsFollow: "follow" | "nofollow" | null;
    schemaType:
      | "Article"
      | "LocalBusiness"
      | "Organization"
      | "Project"
      | "Service"
      | null;
    customSchema: {
      knowsAbout: string | null;
      hasOfferCatalog: Array<string> | null;
    } | null;
    ogTitle: string | null;
    ogDescription: string | null;
    twitterCard: "summary_large_image" | "summary" | null;
  } | null;
} | null;

// Source: src/sanity/lib/queries.ts
// Variable: UN_GOALS_QUERY
// Query: *[_type == "unGoal"] | order(name asc){  _id,  name,  logoNegative{    _type,    asset->{      _id,      url    }  },  logoPositive{    _type,    asset->{      _id,      url    }  }}
export type UN_GOALS_QUERY_RESULT = Array<{
  _id: string;
  name: string;
  logoNegative: {
    _type: "image";
    asset: {
      _id: string;
      url: string | null;
    } | null;
  };
  logoPositive: {
    _type: "image";
    asset: {
      _id: string;
      url: string | null;
    } | null;
  };
}>;

// Source: src/sanity/lib/queries.ts
// Variable: CUSTOMERS_QUERY
// Query: *[_type == "customer"] | order(name asc){  _id,  name,  shortDescription,  mainImage{    hotspot,    crop,    asset->{      _id,      url    }  }}
export type CUSTOMERS_QUERY_RESULT = Array<{
  _id: string;
  name: string;
  shortDescription: string | null;
  mainImage: {
    hotspot: SanityImageHotspot | null;
    crop: SanityImageCrop | null;
    asset: {
      _id: string;
      url: string | null;
    } | null;
  } | null;
}>;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '*[_type == "organization"]{\n  _id,\n  name,\n  type,\n  logoDark{\n    _type,\n    asset->{\n      _id,\n      url,\n    }\n  },\n}': ORGANIZATIONS_QUERY_RESULT;
    '*[_type == "project" && defined(slug.current) && seo.robotsIndex != "noindex"] {\n    "slug": slug.current,\n    _updatedAt\n  }': PROJECTS_SITEMAP_QUERY_RESULT;
    '*[_type == "journal" && defined(slug.current) && seo.robotsIndex != "noindex"] {\n    "slug": slug.current,\n    _updatedAt\n  }': JOURNAL_SITEMAP_QUERY_RESULT;
    '*[_type == "service" && defined(slug.current) && seo.robotsIndex != "noindex"] {\n    "slug": slug.current,\n    _updatedAt\n  }': SERVICES_SITEMAP_QUERY_RESULT;
    '*[_type == "site" && _id == "site"][0]{\n  name,\n  seo{\n    metaTitle,\n    metaDescription,\n    ogImage{\n      asset->{\n        _id,\n        url\n      }\n    },\n    canonicalUrl,\n    robotsIndex,\n    robotsFollow,\n    ogTitle,\n    ogDescription,\n    twitterCard\n  }\n}': SITE_SETTINGS_QUERY_RESULT;
    '*[_type == "project" && defined(slug.current)] {\n  _id,\n  name,\n  slug,\n  shortDescription,\n  gridDimension{\n    isBig\n  },\n  mainImage{\n    _type,\n    image{\n      _type,\n      asset->{\n        _id,\n        url\n      }\n    }\n  },\n  tag->{\n    _id,\n    name\n  }\n}': PROJECTS_QUERY_RESULT;
    '*[_type == "journal" && defined(slug.current)] | order(publishingDate desc){\n  _id,\n  name,\n  slug,\n  shortDescription,\n  gridDimension{\n    isBig\n  },\n  mainImage{\n    _type,\n    image{\n      _type,\n      asset->{\n        _id,\n        url\n      }\n    }\n  },\n  publishingDate,\n  tag->{\n    _id,\n    name\n  }\n}': JOURNAL_QUERY_RESULT;
    '*[_type == "journal" && slug.current == $slug][0]{\n  _id,\n  name,\n  slug,\n  mainImage{\n    _type,\n    image{\n      _type,\n      asset->{\n        _id,\n        url\n      }\n    }\n  },\n  location,\n  publishingDate,\n  shortDescription,\n  contentObject[]{\n    ...,\n    _type == "block" => {\n      ...,\n      markDefs[]{\n        ...,\n        _type == "internalLink" => {\n          ...,\n          "slug": reference->slug.current,\n          "type": reference->_type\n        }\n      }\n    },\n    _type == "imageObject" => {\n      ...,\n      image{\n        ...,\n        hotspot,\n        crop,\n        asset->{\n          _id,\n          url,\n          metadata{\n            dimensions{\n              width,\n              height,\n              aspectRatio\n            }\n          }\n        }\n      }\n    }\n  },\n  tag->{\n    _id,\n    name\n  },\n  seo{\n    metaTitle,\n    metaDescription,\n    ogImage{\n      asset->{\n        _id,\n        url\n      }\n    },\n    canonicalUrl,\n    robotsIndex,\n    robotsFollow,\n    schemaType,\n    customSchema{\n      knowsAbout,\n      hasOfferCatalog\n    },\n    ogTitle,\n    ogDescription,\n    twitterCard\n  }\n}': JOURNAL_ITEM_QUERY_RESULT;
    '*[_type == "tag"] | order(name asc){\n  _id,\n  name,\n  slug\n}': TAGS_QUERY_RESULT;
    '*[_type == "service" && defined(slug.current)] | order(name asc){\n  _id,\n  name,\n  slug,\n  shortDescription,\n  mainImage{\n    _type,\n    image{\n      _type,\n      asset->{\n        _id,\n        url\n      }\n    }\n  }\n}': SERVICES_QUERY_RESULT;
    '*[_type == "service" && slug.current == $slug][0]{\n  _id,\n  name,\n  slug,\n  shortDescription,\n\n  content[]{\n    ...,\n    _type == "block" => {\n      ...,\n      markDefs[]{\n        ...,\n        _type == "internalLink" => {\n          ...,\n          "slug": reference->slug.current,\n          "type": reference->_type\n        }\n      }\n    },\n    _type == "imageObject" => {\n      ...,\n      image{\n        ...,\n        hotspot,\n        crop,\n        asset->{\n          _id,\n          url,\n          metadata{\n            dimensions{\n              width,\n              height,\n              aspectRatio\n            }\n          }\n        }\n      }\n    }\n  },\n  capabilities[]->{\n    _id,\n    name\n  },\n  clients[]->{\n    _id,\n    name,\n    logoDark{\n      asset->{\n        _id,\n        _type,\n        url\n      }\n    }\n  },\n  mainImage{\n    image{\n      asset->{\n        url\n      }\n    }\n  },\n  seo{\n    metaTitle,\n    metaDescription,\n    ogImage{\n      asset->{\n        _id,\n        url\n      }\n    },\n    canonicalUrl,\n    robotsIndex,\n    robotsFollow,\n    schemaType,\n    customSchema{\n      knowsAbout,\n      hasOfferCatalog\n    },\n    ogTitle,\n    ogDescription,\n    twitterCard\n  }\n}': SERVICE_QUERY_RESULT;
    '*[_type == "project" && slug.current == $slug][0]{\n  _id,\n  name,\n  slug,\n  mainImage{\n    _type,\n    image{\n      _type,\n      asset->{\n        _id,\n        url\n      }\n    }\n  },\n  status,\n  location,\n  areaRestored,\n  interventionType,\n  shortDescription,\n  pageContent{\n    content[]{\n      ...,\n      _type == "block" => {\n        ...,\n        markDefs[]{\n          ...,\n          _type == "internalLink" => {\n            ...,\n            "slug": reference->slug.current,\n            "type": reference->_type\n          }\n        }\n      },\n      _type == "imageObject" => {\n        ...,\n        image{\n          ...,\n          hotspot,\n          crop,\n          asset->{\n            _id,\n            url,\n            metadata{\n              dimensions{\n                width,\n                height,\n                aspectRatio\n              }\n            }\n          }\n        }\n      }\n    }\n  },\n  relatedService->{\n    _id,\n    name,\n    slug\n  },\n  relatedResearch->{\n    _id,\n    name\n  },\n  seo{\n    metaTitle,\n    metaDescription,\n    ogImage{\n      asset->{\n        _id,\n        url\n      }\n    },\n    canonicalUrl,\n    robotsIndex,\n    robotsFollow,\n    schemaType,\n    customSchema{\n      knowsAbout,\n      hasOfferCatalog\n    },\n    ogTitle,\n    ogDescription,\n    twitterCard\n  }\n}': PROJECT_ITEM_QUERY_RESULT;
    '*[_type == "unGoal"] | order(name asc){\n  _id,\n  name,\n  logoNegative{\n    _type,\n    asset->{\n      _id,\n      url\n    }\n  },\n  logoPositive{\n    _type,\n    asset->{\n      _id,\n      url\n    }\n  }\n}': UN_GOALS_QUERY_RESULT;
    '*[_type == "customer"] | order(name asc){\n  _id,\n  name,\n  shortDescription,\n  mainImage{\n    hotspot,\n    crop,\n    asset->{\n      _id,\n      url\n    }\n  }\n}': CUSTOMERS_QUERY_RESULT;
  }
}
